version: '3.1'

services:
  client:
    tty: true
    restart: always
    image: node:18.0.0
    command: [bash, -c, "cd ./code/cmd/web && npm install && npm run start"]
    ports:
      - 9000:9000
    volumes:
      - .:/code
  
  server:
    tty: true
    image: golang:1.20-buster
    restart: always
    volumes:
    - .:/code
  
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    volumes:
      - .:/code
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: